version: '3.9'

services:
  flask_app:
    build:
      context: ./flask_app
    image:  crc_dev
    restart: unless-stopped

    ports: 
      - 5000:5000
    env_file:
      - ./.env
    # depends_on:
    #   - db

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - flask_app

    

#     networks:
#       - flask_network    

# networks:
#   flask_network:
